=== ARosemary/oq-engine/docs/schema/nrml_seismic.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:gml="http://www.opengis.net/gml"
           xmlns:nrml="http://openquake.org/xmlns/nrml/0.1"
           xmlns="http://openquake.org/xmlns/nrml/0.1"
           targetNamespace="http://openquake.org/xmlns/nrml/0.1"
           elementFormDefault="qualified">

    <xs:annotation>
        <xs:documentation xml:lang="en">Schema describing the XML structure of files containing information pertinent with the creation of ERF.
        </xs:documentation>
    </xs:annotation>

    <xs:import namespace="http://www.opengis.net/gml" schemaLocation="./gmlsf.xsd"/>
    <xs:include schemaLocation="nrml_common.xsd"/>

    <!-- ============================================================= -->

    <xs:simpleType name="Strike">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="0.0"/>
            <xs:maxInclusive value="360.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Dip">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="0.0"/>
            <xs:maxInclusive value="90.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Rake">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="-180.0"/>
            <xs:maxInclusive value="+180.0"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TectonicRegion">
        <xs:restriction base="xs:string">
            
            <!-- NOTE: made enum values lowercase and removed whitespace, in order
                 to match style of other enums -->
            <xs:enumeration value="active_shallow_crust"/>
            <xs:enumeration value="stable_shallow_crust"/>
            <xs:enumeration value="subduction_interface"/>
            <xs:enumeration value="subduction_intra_slab"/>
            <xs:enumeration value="volcanic"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="FocalMechanism">
        <xs:sequence>
            <xs:element name="strike" type="Strike"/>
            <xs:element name="dip" type="Dip"/>
            <xs:element name="rake" type="Rake"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="TruncatedGutenbergRichter">
        <xs:sequence>
            <xs:element name="aValueCumulative" type="xs:double"/>
            <xs:element name="bValue" type="NonNegativeDoubleType"/>
            <xs:element name="minMagnitude" type="Magnitude"/>
            <xs:element name="maxMagnitude" type="Magnitude"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="magnitudeFrequencyDistribution" abstract="true"/>
    <xs:element name="truncatedGutenbergRichter" type="TruncatedGutenbergRichter"
        substitutionGroup="magnitudeFrequencyDistribution"/>
    <xs:element name="evenlyDiscretizedIncrementalMagFreqDist" type="EvenlyDiscretizedDist"
        substitutionGroup="magnitudeFrequencyDistribution"/>

    <xs:complexType name="RuptureRateModel">
        <xs:sequence>
            <xs:element ref="magnitudeFrequencyDistribution"/>
            <xs:element name="focalMechanism" type="FocalMechanism"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SourceData">
        <xs:sequence>
            <xs:element name="sourceName" type="xs:string"/>
            <xs:element name="sourceID" type="xs:string"/>
            <xs:element name="tectonicRegion" type="TectonicRegion"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SimpleFaultGeometry">
        <xs:sequence>
            <xs:element name="faultTrace" type="gml:LineStringType"/>
            <xs:element name="dip" type="nrml:Dip"/>
            <xs:element name="upperSeismogenicDepth" type="NonNegativeDoubleType"/>
            <xs:element name="lowerSeismogenicDepth" type="NonNegativeDoubleType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SimpleFaultSourceData">
        <xs:complexContent>
            <xs:extension base="SourceData">
                <xs:sequence>
                    <xs:element name="simpleFaultGeometry" type="SimpleFaultGeometry"/>
                    <xs:element name="rake" type="Rake"/>
                    <xs:element ref="magnitudeFrequencyDistribution"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ComplexFaultGeometry">
        <xs:sequence>
            <xs:element name="faultTopEdge" type="gml:LineStringType"/>
            <xs:element name="faultBottomEdge" type="gml:LineStringType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ComplexFaultSourceData">
        <xs:complexContent>
            <xs:extension base="SourceData">
                <xs:sequence>
                    <xs:element name="complexFaultGeometry" type="ComplexFaultGeometry"/>
                    <xs:element name="rake" type="Rake"/>
                    <xs:element ref="magnitudeFrequencyDistribution"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="AreaSourceData">
        <xs:complexContent>
            <xs:extension base="SourceData">
                <xs:sequence>
                    <xs:element name="areaBoundary" type="gml:PolygonType"/>
                    <xs:sequence minOccurs="1" maxOccurs="unbounded">
                        <xs:element name="ruptureRateModel" type="RuptureRateModel"/>
                    </xs:sequence>
                    <xs:element name="ruptureDepthDistribution" type="ArbitrarilyDiscretizedDist"/>
                    <xs:element name="hypocentralDepth" type="NonNegativeDoubleType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="PointSourceData">
        <xs:complexContent>
            <xs:extension base="SourceData">
                <xs:sequence>
                    <xs:element name="pointLocation" type="gml:PointType"/>
                    <xs:sequence minOccurs="1" maxOccurs="unbounded">
                        <xs:element name="ruptureRateModel" type="RuptureRateModel"/>
                    </xs:sequence>
                    <xs:element name="ruptureDepthDistribution" type="ArbitrarilyDiscretizedDist"/>
                    <xs:element name="hypocentralDepth" type="NonNegativeDoubleType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- seismic source -->
    
    <xs:element name="seismicSource" abstract="true"/>
    <xs:element name="simpleFault" type="SimpleFaultSourceData" substitutionGroup="seismicSource"/>
    <xs:element name="complexFault" type="ComplexFaultSourceData" substitutionGroup="seismicSource"/>
    <xs:element name="area" type="AreaSourceData" substitutionGroup="seismicSource"/>
    <xs:element name="point" type="PointSourceData" substitutionGroup="seismicSource"/>

    <xs:element name="sourceModel" type="SourceModel"/>
    <xs:complexType name="SourceModel">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element ref="seismicSource"/>
        </xs:sequence>
    </xs:complexType>

    <!-- rupture -->

    <xs:element name="rupture" type="Rupture" substitutionGroup="gml:_Feature" abstract="true"/>
    <xs:complexType name="Rupture">
        <xs:complexContent>
            <xs:extension base="gml:AbstractFeatureType">
                <xs:sequence>
                    <xs:element name="magnitude" type="Magnitude"/>
                    <xs:element name="tectonicRegion" type="TectonicRegion"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:element name="pointRupture" type="PointRupture" substitutionGroup="rupture"/>
    <xs:complexType name="PointRupture">
        <xs:complexContent>
            <xs:extension base="Rupture">
                <xs:sequence>
                    <xs:element name="focalMechanism" type="FocalMechanism"/>
                    
                    <!-- TODO: use correct geospatial type -->
                    <xs:element name="hypocenterLocation" type="gml:PointType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:element name="simpleFaultRupture" type="SimpleFaultRupture" substitutionGroup="rupture"/>
    <xs:complexType name="SimpleFaultRupture">
        <xs:complexContent>
            <xs:extension base="Rupture">
                <xs:sequence>
                    <xs:element name="rake" type="Rake"/>
                    
                    <!-- TODO: use correct geospatial type -->
                    <xs:element name="simpleFaultGeometry" type="SimpleFaultGeometry"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:element name="complexFaultRupture" type="ComplexFaultRupture" substitutionGroup="rupture"/>
    <xs:complexType name="ComplexFaultRupture">
        <xs:complexContent>
            <xs:extension base="Rupture">
                <xs:sequence>
                    <xs:element name="rake" type="Rake"/>
                    
                    <!-- TODO: use correct geospatial type -->
                    <xs:element name="complexFaultGeometry" type="ComplexFaultGeometry"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    <xs:element name="arbitrarilyComplexRupture" type="ArbitrarilyComplexRupture" substitutionGroup="rupture"/>
    <xs:complexType name="ArbitrarilyComplexRupture">
        <xs:complexContent>
            <xs:extension base="Rupture">
                <xs:sequence>
                    <xs:element name="rake" type="Rake"/>
                    <xs:element name="ruptureSurface" type="gml:SurfacePropertyType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- logic tree -->
    
    <!-- TODO: rename attribute, name is too general for global attribute (make attribute local) -->
    <xs:attribute name="uncertaintyType">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:enumeration value="gmpeModel"/>
                <xs:enumeration value="sourceModel"/>
                <xs:enumeration value="maxMagnitudeGutenbergRichterRelative"/>
                <xs:enumeration value="bValueGutenbergRichterRelative"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
    
    <xs:complexType name="LogicTreeBranch">
        <xs:sequence>
            <xs:element name="uncertaintyModel" type="xs:string"/>
            <xs:element name="uncertaintyWeight" type="NonNegativeDoubleType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="LogicTreeBranchSet">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="logicTreeBranch" type="LogicTreeBranch"/>
        </xs:sequence>
        <xs:attribute ref="uncertaintyType" use="required"/>
    </xs:complexType>

    <xs:complexType name="LogicTree">

        <xs:sequence maxOccurs="unbounded">
            <xs:element name="logicTreeBranchSet" type="LogicTreeBranchSet"/>
        </xs:sequence>
        <xs:attribute name="tectonicRegion" type="TectonicRegion"/>
    </xs:complexType>
    
    <xs:complexType name="LogicTreeSet">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="logicTree" type="LogicTree"></xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="logicTreeSet" type="LogicTreeSet"></xs:element>

</xs:schema>

=== ARosemary/oq-engine/docs/schema/examples/source_model.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns2:sourceModel xmlns:ns1="http://www.opengis.net/gml/profile/sfgml/1.0"
 xmlns:ns2="http://openquake.org/xmlns/nrml/0.1"
 xmlns:ns3="http://www.w3.org/1999/xlink"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://openquake.org/xmlns/nrml/0.1 file:/Users/damianomonelli/Projects/opengem/docs/schema/nrml_seismic.xsd">
     <ns2:simpleFault>
            <ns2:sourceName>Mount Diablo Thrust</ns2:sourceName>
            <ns2:sourceID>src01</ns2:sourceID>
            <ns2:tectonicRegion>Active Shallow Crust</ns2:tectonicRegion>
            <ns2:simpleFaultGeometry>
                <ns2:faultTrace>
                    <ns1:posList>
                        37.73010 -121.82290 0.0
                        37.87710 -122.03880 0.0
                    </ns1:posList>
                </ns2:faultTrace>
                <ns2:dip>38</ns2:dip>
                <ns2:upperSeismogenicDepth>8.0</ns2:upperSeismogenicDepth>
                <ns2:lowerSeismogenicDepth>13.0</ns2:lowerSeismogenicDepth>
            </ns2:simpleFaultGeometry>
            <ns2:rake>90.0</ns2:rake>
         <ns2:evenlyDiscretizedIncrementalMagFreqDist binSize="0.1" minVal="6.55" binCount="5">
             <DistributionValues>0.0010614989 8.8291627E-4 7.3437777E-4 6.108288E-4 5.080653E-4</DistributionValues>
         </ns2:evenlyDiscretizedIncrementalMagFreqDist>
    </ns2:simpleFault>
    <ns2:complexFault>
            <ns2:sourceName>Cascadia Megathrust</ns2:sourceName>
            <ns2:sourceID>src02</ns2:sourceID>
            <ns2:tectonicRegion>Subduction Interface</ns2:tectonicRegion>
            <ns2:complexFaultGeometry>
                <ns2:faultTopEdge>
                    <ns1:posList>
                        40.363  -124.704  0.5493260E+01
                        41.214  -124.977  0.4988560E+01
                        42.096  -125.140  0.4897340E+01
                        42.965  -125.219  0.4847610E+01
                        43.852  -125.257  0.4871280E+01
                        44.718  -125.313  0.4782420E+01
                        45.458  -125.416  0.4410880E+01
                        46.337  -125.623  0.4028170E+01
                        46.642  -125.746  0.3797400E+01
                        46.965  -125.874  0.3649880E+01
                        47.289  -126.015  0.3650670E+01
                        47.661  -126.240  0.3675160E+01
                        47.994  -126.422  0.3907950E+01
                        48.287  -126.660  0.4125160E+01
                        48.711  -127.037  0.4583670E+01
                        49.279  -127.605  0.4761580E+01
                    </ns1:posList>
                </ns2:faultTopEdge>
                <ns2:faultBottomEdge>
                    <ns1:posList>
                        40.347  -123.829  0.2038490E+02
                        41.218  -124.137  0.1741390E+02
                        42.115  -124.252  0.1752740E+02
                        42.984  -124.313  0.1729190E+02
                        43.868  -124.263  0.1856200E+02
                        44.740  -124.213  0.1977810E+02
                        45.494  -124.099  0.2230320E+02
                        46.369  -123.853  0.2575860E+02
                        46.811  -123.644  0.2711490E+02
                        47.300  -123.423  0.2761730E+02
                        47.792  -123.440  0.2750930E+02
                        48.221  -124.075  0.2602160E+02
                        48.560  -124.773  0.2572870E+02
                        48.873  -125.409  0.2544710E+02
                        49.244  -126.117  0.2471340E+02
                        49.687  -126.911  0.2275770E+02
                    </ns1:posList>
                </ns2:faultBottomEdge>
            </ns2:complexFaultGeometry>
            <ns2:rake>0.0</ns2:rake>
            <ns2:truncatedGutenbergRichter>
                <ns2:aValueCumulative>1.0</ns2:aValueCumulative>
                <ns2:bValue>0.8</ns2:bValue>
                <ns2:minMagnitude>6.5</ns2:minMagnitude>
                <ns2:maxMagnitude>9.0</ns2:maxMagnitude>
            </ns2:truncatedGutenbergRichter>
    </ns2:complexFault>
    <ns2:area>
            <ns2:sourceName>Quito</ns2:sourceName>
            <ns2:sourceID>src03</ns2:sourceID>
            <ns2:tectonicRegion>Active Shallow Crust</ns2:tectonicRegion>
            <ns2:areaBoundary>
                 <ns1:exterior>
                     <ns1:LinearRing>
                         <ns1:posList>            
                             37.5 -122.5
                             37.5 -121.5
                             38.5 -121.5
                             38.5 -122.5
                     </ns1:posList>
                  </ns1:LinearRing>
             </ns1:exterior>
            </ns2:areaBoundary>
                <ns2:ruptureRateModel>
                    <ns2:truncatedGutenbergRichter>
                        <ns2:aValueCumulative>5.0</ns2:aValueCumulative>
                        <ns2:bValue>0.8</ns2:bValue>
                        <ns2:minMagnitude>5.0</ns2:minMagnitude>
                        <ns2:maxMagnitude>7.0</ns2:maxMagnitude>
                    </ns2:truncatedGutenbergRichter>
                    <ns2:focalMechanism>
                        <ns2:strike>0.0</ns2:strike>
                        <ns2:dip>90.0</ns2:dip>
                        <ns2:rake>0.0</ns2:rake>
                    </ns2:focalMechanism>
                    <ns2:ruptureDepthDistribution>
                        <XValues>6.0 6.5 7.0</XValues>
                        <YValues>5.0 3.0 0.0</YValues>
                    </ns2:ruptureDepthDistribution>
                </ns2:ruptureRateModel>
            <ns2:hypocentralDepth>5.0</ns2:hypocentralDepth>
    </ns2:area>
    <ns2:point>
        <ns2:sourceName>point</ns2:sourceName>
            <ns2:sourceID>src04</ns2:sourceID>
            <ns2:tectonicRegion>Active Shallow Crust</ns2:tectonicRegion>
            <ns2:pointLocation>
                <ns1:pos>38.0 -122.0</ns1:pos>
            </ns2:pointLocation>
                <ns2:ruptureRateModel>
                    <ns2:truncatedGutenbergRichter>
                        <ns2:aValueCumulative>0.5</ns2:aValueCumulative>
                        <ns2:bValue>0.8</ns2:bValue>
                        <ns2:minMagnitude>5.0</ns2:minMagnitude>
                        <ns2:maxMagnitude>7.0</ns2:maxMagnitude>
                    </ns2:truncatedGutenbergRichter>
                    <ns2:focalMechanism>
                        <ns2:strike>0.0</ns2:strike>
                        <ns2:dip>90.0</ns2:dip>
                        <ns2:rake>0.0</ns2:rake>
                    </ns2:focalMechanism>
                    <ns2:ruptureDepthDistribution>
                        <XValues>6.0 6.5 3.0</XValues>
                        <YValues>5.0 3.0 0.0</YValues>
                    </ns2:ruptureDepthDistribution>
                </ns2:ruptureRateModel>
            <ns2:hypocentralDepth>5</ns2:hypocentralDepth>
    </ns2:point>
</ns2:sourceModel>
